package entity;
// Generated 19 mai 2017 15:58:01 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Clients generated by hbm2java
 */
public class Clients  implements java.io.Serializable {


     private Integer id;
     private String nom;
     private String adresse;
     private String telephone;
     private Date createdAt;
     private Date updatedAt;
     private Set venteses = new HashSet(0);

    public Clients() {
    }

	
    public Clients(String nom, String adresse, String telephone) {
        this.nom = nom;
        this.adresse = adresse;
        this.telephone = telephone;
    }
    public Clients(String nom, String adresse, String telephone, Date createdAt, Date updatedAt, Set venteses) {
       this.nom = nom;
       this.adresse = adresse;
       this.telephone = telephone;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.venteses = venteses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getVenteses() {
        return this.venteses;
    }
    
    public void setVenteses(Set venteses) {
        this.venteses = venteses;
    }




}


