package entity;
// Generated 19 mai 2017 15:58:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Produits generated by hbm2java
 */
public class Produits  implements java.io.Serializable {


     private Integer id;
     private String libelle;
     private BigDecimal qte;
     private String type;
     private Date createdAt;
     private Date updatedAt;
     private Set achatses = new HashSet(0);
     private Set venteses = new HashSet(0);

    public Produits() {
    }

	
    public Produits(String libelle, BigDecimal qte, String type) {
        this.libelle = libelle;
        this.qte = qte;
        this.type = type;
    }
    public Produits(String libelle, BigDecimal qte, String type, Date createdAt, Date updatedAt, Set achatses, Set venteses) {
       this.libelle = libelle;
       this.qte = qte;
       this.type = type;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
       this.achatses = achatses;
       this.venteses = venteses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLibelle() {
        return this.libelle;
    }
    
    public void setLibelle(String libelle) {
        this.libelle = libelle;
    }
    public BigDecimal getQte() {
        return this.qte;
    }
    
    public void setQte(BigDecimal qte) {
        this.qte = qte;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
    public Set getAchatses() {
        return this.achatses;
    }
    
    public void setAchatses(Set achatses) {
        this.achatses = achatses;
    }
    public Set getVenteses() {
        return this.venteses;
    }
    
    public void setVenteses(Set venteses) {
        this.venteses = venteses;
    }




}


