package entity;
// Generated 19 mai 2017 15:58:01 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Utilisateurs generated by hbm2java
 */
public class Utilisateurs  implements java.io.Serializable {


     private Integer id;
     private String login;
     private String password;
     private String nom;
     private String prenom;
     private String telephone;
     private String type;
     private Date createdAt;
     private Date updatedAt;

    public Utilisateurs() {
    }

	
    public Utilisateurs(String login, String password, String nom, String prenom, String telephone, String type) {
        this.login = login;
        this.password = password;
        this.nom = nom;
        this.prenom = prenom;
        this.telephone = telephone;
        this.type = type;
    }
    public Utilisateurs(String login, String password, String nom, String prenom, String telephone, String type, Date createdAt, Date updatedAt) {
       this.login = login;
       this.password = password;
       this.nom = nom;
       this.prenom = prenom;
       this.telephone = telephone;
       this.type = type;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }
    public String getPrenom() {
        return this.prenom;
    }
    
    public void setPrenom(String prenom) {
        this.prenom = prenom;
    }
    public String getTelephone() {
        return this.telephone;
    }
    
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Override
    public String toString() {
        return nom + " " + prenom;
    }




}


