package entity;
// Generated 19 mai 2017 15:58:01 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Ventes generated by hbm2java
 */
public class Ventes  implements java.io.Serializable {


     private Integer id;
     private Clients clients;
     private Produits produits;
     private Date dateVente;
     private String qteVendue;
     private BigDecimal prixVente;
     private Date createdAt;
     private Date updatedAt;

    public Ventes() {
    }

	
    public Ventes(Clients clients, Produits produits, Date dateVente, String qteVendue, BigDecimal prixVente) {
        this.clients = clients;
        this.produits = produits;
        this.dateVente = dateVente;
        this.qteVendue = qteVendue;
        this.prixVente = prixVente;
    }
    public Ventes(Clients clients, Produits produits, Date dateVente, String qteVendue, BigDecimal prixVente, Date createdAt, Date updatedAt) {
       this.clients = clients;
       this.produits = produits;
       this.dateVente = dateVente;
       this.qteVendue = qteVendue;
       this.prixVente = prixVente;
       this.createdAt = createdAt;
       this.updatedAt = updatedAt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Clients getClients() {
        return this.clients;
    }
    
    public void setClients(Clients clients) {
        this.clients = clients;
    }
    public Produits getProduits() {
        return this.produits;
    }
    
    public void setProduits(Produits produits) {
        this.produits = produits;
    }
    public Date getDateVente() {
        return this.dateVente;
    }
    
    public void setDateVente(Date dateVente) {
        this.dateVente = dateVente;
    }
    public String getQteVendue() {
        return this.qteVendue;
    }
    
    public void setQteVendue(String qteVendue) {
        this.qteVendue = qteVendue;
    }
    public BigDecimal getPrixVente() {
        return this.prixVente;
    }
    
    public void setPrixVente(BigDecimal prixVente) {
        this.prixVente = prixVente;
    }
    public Date getCreatedAt() {
        return this.createdAt;
    }
    
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }
    public Date getUpdatedAt() {
        return this.updatedAt;
    }
    
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }




}


